//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLStudio.Core.Modules.StartPage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StartPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StartPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLStudio.Core.Modules.StartPage.Resources.StartPageResources", typeof(StartPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a project template with code scaffolding to get started.
        /// </summary>
        public static string ChooseAProjectTemplateWithCodeScaffoldingToGetStarted {
            get {
                return ResourceManager.GetString("ChooseAProjectTemplateWithCodeScaffoldingToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All From List.
        /// </summary>
        public static string ClearAllRecentFiles {
            get {
                return ResourceManager.GetString("ClearAllRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone a repository.
        /// </summary>
        public static string CloneARepository {
            get {
                return ResourceManager.GetString("CloneARepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue without code.
        /// </summary>
        public static string ContinueWithoutCode {
            get {
                return ResourceManager.GetString("ContinueWithoutCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path.
        /// </summary>
        public static string CopyPath {
            get {
                return ResourceManager.GetString("CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new project.
        /// </summary>
        public static string CreateANewProject {
            get {
                return ResourceManager.GetString("CreateANewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get code from an online repository like GitHub or Azure DevOps.
        /// </summary>
        public static string GetCodeFromAnOnlineRepository {
            get {
                return ResourceManager.GetString("GetCodeFromAnOnlineRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate and edit within any folder.
        /// </summary>
        public static string NavigateAndEditWithinAnyFolder {
            get {
                return ResourceManager.GetString("NavigateAndEditWithinAnyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a local folder.
        /// </summary>
        public static string OpenALocalFolder {
            get {
                return ResourceManager.GetString("OpenALocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a local SLStudio project or .sls file.
        /// </summary>
        public static string OpenALocalSLStudioProjectOrSlsFile {
            get {
                return ResourceManager.GetString("OpenALocalSLStudioProjectOrSlsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a project or solution.
        /// </summary>
        public static string OpenAProjectOrSolution {
            get {
                return ResourceManager.GetString("OpenAProjectOrSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open local solution.
        /// </summary>
        public static string OpenLocalSolution {
            get {
                return ResourceManager.GetString("OpenLocalSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open recent.
        /// </summary>
        public static string OpenRecent {
            get {
                return ResourceManager.GetString("OpenRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned.
        /// </summary>
        public static string Pinned {
            get {
                return ResourceManager.GetString("Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin this item to the Recent Projects list.
        /// </summary>
        public static string PinThisItemToTheRecentProjectsList {
            get {
                return ResourceManager.GetString("PinThisItemToTheRecentProjectsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From List.
        /// </summary>
        public static string RemoveFromList {
            get {
                return ResourceManager.GetString("RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search recent (Alt+S).
        /// </summary>
        public static string SearchRecent {
            get {
                return ResourceManager.GetString("SearchRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Page.
        /// </summary>
        public static string StartPage {
            get {
                return ResourceManager.GetString("StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin this item from the Recent Projects list.
        /// </summary>
        public static string UnpinThisItemFromTheRecentProjectsList {
            get {
                return ResourceManager.GetString("UnpinThisItemFromTheRecentProjectsList", resourceCulture);
            }
        }
    }
}
