//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLStudio.ViewsExtensions.Themes {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class DefaultTheme : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefaultTheme defaultInstance = ((DefaultTheme)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefaultTheme())));
        
        public static DefaultTheme Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238, 238, 242")]
        public global::System.Drawing.Color styleTheme {
            get {
                return ((global::System.Drawing.Color)(this["styleTheme"]));
            }
            set {
                this["styleTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28, 151, 234")]
        public global::System.Drawing.Color styleBase {
            get {
                return ((global::System.Drawing.Color)(this["styleBase"]));
            }
            set {
                this["styleBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 122, 204")]
        public global::System.Drawing.Color styleSelected {
            get {
                return ((global::System.Drawing.Color)(this["styleSelected"]));
            }
            set {
                this["styleSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12, 12, 12")]
        public global::System.Drawing.Color styleFont {
            get {
                return ((global::System.Drawing.Color)(this["styleFont"]));
            }
            set {
                this["styleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 82, 175")]
        public global::System.Drawing.Color styleBorders {
            get {
                return ((global::System.Drawing.Color)(this["styleBorders"]));
            }
            set {
                this["styleBorders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("195, 195, 198")]
        public global::System.Drawing.Color styleThemeExtras {
            get {
                return ((global::System.Drawing.Color)(this["styleThemeExtras"]));
            }
            set {
                this["styleThemeExtras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 102, 204")]
        public global::System.Drawing.Color styleLink {
            get {
                return ((global::System.Drawing.Color)(this["styleLink"]));
            }
            set {
                this["styleLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252, 252, 253")]
        public global::System.Drawing.Color styleSelection {
            get {
                return ((global::System.Drawing.Color)(this["styleSelection"]));
            }
            set {
                this["styleSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28, 151, 234")]
        public global::System.Drawing.Color styleSelection2 {
            get {
                return ((global::System.Drawing.Color)(this["styleSelection2"]));
            }
            set {
                this["styleSelection2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color styleWorkspace {
            get {
                return ((global::System.Drawing.Color)(this["styleWorkspace"]));
            }
            set {
                this["styleWorkspace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("229, 20, 0")]
        public global::System.Drawing.Color styleError {
            get {
                return ((global::System.Drawing.Color)(this["styleError"]));
            }
            set {
                this["styleError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 204, 0")]
        public global::System.Drawing.Color styleWarning {
            get {
                return ((global::System.Drawing.Color)(this["styleWarning"]));
            }
            set {
                this["styleWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27, 161, 226")]
        public global::System.Drawing.Color styleInfo {
            get {
                return ((global::System.Drawing.Color)(this["styleInfo"]));
            }
            set {
                this["styleInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color styleFontMask {
            get {
                return ((global::System.Drawing.Color)(this["styleFontMask"]));
            }
            set {
                this["styleFontMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color styleFontLight {
            get {
                return ((global::System.Drawing.Color)(this["styleFontLight"]));
            }
            set {
                this["styleFontLight"] = value;
            }
        }
    }
}
