//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2013 - 2020 LoadingIndicators.WPF")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("A collection of 8 animated loading indicators for WPF.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0.0+65babeca72f36aa9ac55cfab449c2d3293bd53cd")]
[assembly: System.Reflection.AssemblyProductAttribute("LoadingIndicators.WPF")]
[assembly: System.Reflection.AssemblyTitleAttribute("LoadingIndicators.WPF")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

