//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLStudio.Core.Modules.LogsVisualizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogsVisualizerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogsVisualizerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLStudio.Core.Modules.LogsVisualizer.Resources.LogsVisualizerResources", typeof(LogsVisualizerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export All.
        /// </summary>
        public static string button_exportAll {
            get {
                return ResourceManager.GetString("button_exportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ok.
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete all logs from the database
        ///Are you sure you want to continue?.
        /// </summary>
        public static string dialog_message_clearConfirmation {
            get {
                return ResourceManager.GetString("dialog_message_clearConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Logs.
        /// </summary>
        public static string dialog_title_clearLogs {
            get {
                return ResourceManager.GetString("dialog_title_clearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Logs to HTML.
        /// </summary>
        public static string dialog_title_exportHtml {
            get {
                return ResourceManager.GetString("dialog_title_exportHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Logs to Text.
        /// </summary>
        public static string dialog_title_exportTxt {
            get {
                return ResourceManager.GetString("dialog_title_exportTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML File (*.html)|*.html.
        /// </summary>
        public static string filter_htmlFile {
            get {
                return ResourceManager.GetString("filter_htmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File (*.txt)|*.txt.
        /// </summary>
        public static string filter_textFile {
            get {
                return ResourceManager.GetString("filter_textFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string header_date {
            get {
                return ResourceManager.GetString("header_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string header_id {
            get {
                return ResourceManager.GetString("header_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string header_level {
            get {
                return ResourceManager.GetString("header_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string header_message {
            get {
                return ResourceManager.GetString("header_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string header_sender {
            get {
                return ResourceManager.GetString("header_sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string header_title {
            get {
                return ResourceManager.GetString("header_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string label_date {
            get {
                return ResourceManager.GetString("label_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string label_id {
            get {
                return ResourceManager.GetString("label_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string label_level {
            get {
                return ResourceManager.GetString("label_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string label_message {
            get {
                return ResourceManager.GetString("label_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender:.
        /// </summary>
        public static string label_sender {
            get {
                return ResourceManager.GetString("label_sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string label_title {
            get {
                return ResourceManager.GetString("label_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string statusbar_status_ready {
            get {
                return ResourceManager.GetString("statusbar_status_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        public static string statusbar_status_working {
            get {
                return ResourceManager.GetString("statusbar_status_working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Logs: {0}.
        /// </summary>
        public static string statusbar_totalLogsFormat {
            get {
                return ResourceManager.GetString("statusbar_totalLogsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Size: {0}.
        /// </summary>
        public static string statusbar_totalSizeFormat {
            get {
                return ResourceManager.GetString("statusbar_totalSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string tooltip_clearAll {
            get {
                return ResourceManager.GetString("tooltip_clearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to HTML (Ctrl+E).
        /// </summary>
        public static string tooltip_exportToHtml {
            get {
                return ResourceManager.GetString("tooltip_exportToHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh (F5).
        /// </summary>
        public static string tooltip_refresh {
            get {
                return ResourceManager.GetString("tooltip_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Simple Logs.
        /// </summary>
        public static string tooltip_viewSimpleLogs {
            get {
                return ResourceManager.GetString("tooltip_viewSimpleLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Details.
        /// </summary>
        public static string window_title_Details {
            get {
                return ResourceManager.GetString("window_title_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string window_title_logs {
            get {
                return ResourceManager.GetString("window_title_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Logs.
        /// </summary>
        public static string window_title_SimpleLog {
            get {
                return ResourceManager.GetString("window_title_SimpleLog", resourceCulture);
            }
        }
    }
}
