//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLStudio.Core.Menus.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLStudio.Core.Menus.Resources.MenuResources", typeof(MenuResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        internal static string file_close {
            get {
                return ResourceManager.GetString("file/close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        internal static string file_new {
            get {
                return ResourceManager.GetString("file/new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File....
        /// </summary>
        internal static string file_new_newFile {
            get {
                return ResourceManager.GetString("file/new/newFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        internal static string file_open {
            get {
                return ResourceManager.GetString("file/open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File....
        /// </summary>
        internal static string file_open_openFile {
            get {
                return ResourceManager.GetString("file/open/openFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        internal static string file_save {
            get {
                return ResourceManager.GetString("file/save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save {0}.
        /// </summary>
        internal static string file_save_format {
            get {
                return ResourceManager.GetString("file/save_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save A_ll.
        /// </summary>
        internal static string file_saveAll {
            get {
                return ResourceManager.GetString("file/saveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        internal static string file_saveAs {
            get {
                return ResourceManager.GetString("file/saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} _As....
        /// </summary>
        internal static string file_saveAs_format {
            get {
                return ResourceManager.GetString("file/saveAs_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start _Page.
        /// </summary>
        internal static string file_startPage {
            get {
                return ResourceManager.GetString("file/startPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Logs....
        /// </summary>
        internal static string help_logs {
            get {
                return ResourceManager.GetString("help/logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        internal static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options....
        /// </summary>
        internal static string tools_options {
            get {
                return ResourceManager.GetString("tools/options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Output.
        /// </summary>
        internal static string view_output {
            get {
                return ResourceManager.GetString("view/output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Toolbox.
        /// </summary>
        internal static string view_toolbox {
            get {
                return ResourceManager.GetString("view/toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        internal static string window {
            get {
                return ResourceManager.GetString("window", resourceCulture);
            }
        }
    }
}
