//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLStudio.Core.Modules.Options.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OptionsResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OptionsResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLStudio.Core.Modules.Options.Resources.OptionsResx", typeof(OptionsResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        public static string Accent {
            get {
                return ResourceManager.GetString("Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes.
        /// </summary>
        public static string DiscardChanges {
            get {
                return ResourceManager.GetString("DiscardChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard all changes?.
        /// </summary>
        public static string DiscardChangesDialog {
            get {
                return ResourceManager.GetString("DiscardChangesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast splash screen.
        /// </summary>
        public static string FastSplashScreen {
            get {
                return ResourceManager.GetString("FastSplashScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes needs to restart the application in order to be applied.
        /// </summary>
        public static string NeedsRestart {
            get {
                return ResourceManager.GetString("NeedsRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes needs to restart the application in order to be applied
        ///Would you like to restart the application now?.
        /// </summary>
        public static string NeedsRestartDialog {
            get {
                return ResourceManager.GetString("NeedsRestartDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application.
        /// </summary>
        public static string NeedsRestartTitle {
            get {
                return ResourceManager.GetString("NeedsRestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsName {
            get {
                return ResourceManager.GetString("OptionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview themes.
        /// </summary>
        public static string PreviewThemes {
            get {
                return ResourceManager.GetString("PreviewThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset to default settings?.
        /// </summary>
        public static string ResertToDefaultDialog {
            get {
                return ResourceManager.GetString("ResertToDefaultDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resert to default.
        /// </summary>
        public static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show start screen.
        /// </summary>
        public static string ShowInitialScreen {
            get {
                return ResourceManager.GetString("ShowInitialScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splash screen sleep time (ms).
        /// </summary>
        public static string SplashScreenSleepTime {
            get {
                return ResourceManager.GetString("SplashScreenSleepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
    }
}
