//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLStudio.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class frmStartScreen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmStartScreen() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLStudio.Resources.Forms.frmStartScreen", typeof(frmStartScreen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone or checkout project.
        /// </summary>
        public static string button_clone_checkout {
            get {
                return ResourceManager.GetString("button_clone_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new project.
        /// </summary>
        public static string button_create_new {
            get {
                return ResourceManager.GetString("button_create_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a project or solution.
        /// </summary>
        public static string button_open_solution {
            get {
                return ResourceManager.GetString("button_open_solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string button_tutorials {
            get {
                return ResourceManager.GetString("button_tutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string label_get_started {
            get {
                return ResourceManager.GetString("label_get_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open recent.
        /// </summary>
        public static string label_open_recent {
            get {
                return ResourceManager.GetString("label_open_recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL Studio 2019.
        /// </summary>
        public static string label_slstudio {
            get {
                return ResourceManager.GetString("label_slstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue without code.
        /// </summary>
        public static string link_continue {
            get {
                return ResourceManager.GetString("link_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLStudio.
        /// </summary>
        public static string startScreen {
            get {
                return ResourceManager.GetString("startScreen", resourceCulture);
            }
        }
    }
}
