//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLStudio.RpkEditor.Modules.Toolbox.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class ToolboxSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ToolboxSettings defaultInstance = ((ToolboxSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ToolboxSettings())));
        
        public static ToolboxSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>default</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PinnedItems {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PinnedItems"]));
            }
            set {
                this["PinnedItems"] = value;
            }
        }
    }
}
