//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLStudio.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StudioResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudioResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLStudio.Core.Resources.StudioResources", typeof(StudioResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key combination ({0}) is not a command..
        /// </summary>
        public static string CombinationIsNotACommand {
            get {
                return ResourceManager.GetString("CombinationIsNotACommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*)|*.*.
        /// </summary>
        public static string filter_allFiles {
            get {
                return ResourceManager.GetString("filter_allFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Files.
        /// </summary>
        public static string filter_allSupportedFiles {
            get {
                return ResourceManager.GetString("filter_allSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string HumanizerDateTimeToday {
            get {
                return ResourceManager.GetString("HumanizerDateTimeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading assembly {0}....
        /// </summary>
        public static string LoadingAssemblyAssemblyName {
            get {
                return ResourceManager.GetString("LoadingAssemblyAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging resources for {0}....
        /// </summary>
        public static string MergingResources {
            get {
                return ResourceManager.GetString("MergingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering {0}....
        /// </summary>
        public static string RegisteringModule {
            get {
                return ResourceManager.GetString("RegisteringModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {0}....
        /// </summary>
        public static string RunningModule {
            get {
                return ResourceManager.GetString("RunningModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item(s) Saved.
        /// </summary>
        public static string statusbar_status_fileSaved {
            get {
                return ResourceManager.GetString("statusbar_status_fileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string StudioSearchTextBoxStyle_tooltip_clear {
            get {
                return ResourceManager.GetString("StudioSearchTextBoxStyle_tooltip_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string StudioSearchTextBoxStyle_tooltip_search {
            get {
                return ResourceManager.GetString("StudioSearchTextBoxStyle_tooltip_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string toolbox_displayName {
            get {
                return ResourceManager.GetString("toolbox_displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled {0}.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) was pressed. Waiting for next key of chord....
        /// </summary>
        public static string WaitingForNextKeyOfChord {
            get {
                return ResourceManager.GetString("WaitingForNextKeyOfChord", resourceCulture);
            }
        }
    }
}
