//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLStudio.Core.Services.ThemeManager.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class ThemeManagerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ThemeManagerSettings defaultInstance = ((ThemeManagerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ThemeManagerSettings())));
        
        public static ThemeManagerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SLStudio.Light")]
        public string UserTheme {
            get {
                return ((string)(this["UserTheme"]));
            }
            set {
                this["UserTheme"] = value;
            }
        }
    }
}
