//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLStudio.Core.Controls.StudioTextEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextEditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextEditorResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SLStudio.Core.Controls.StudioTextEditor.Resources.TextEditorResources", typeof(TextEditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _Cancel.
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _OK.
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _Line number (1 - {0}):.
        /// </summary>
        public static string label_lineNumber_format {
            get {
                return ResourceManager.GetString("label_lineNumber_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Searching....
        /// </summary>
        public static string label_searching {
            get {
                return ResourceManager.GetString("label_searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} results found.
        /// </summary>
        public static string label_searchResult_format_plural {
            get {
                return ResourceManager.GetString("label_searchResult_format_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} result found.
        /// </summary>
        public static string label_searchResult_format_singular {
            get {
                return ResourceManager.GetString("label_searchResult_format_singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close (Esc).
        /// </summary>
        public static string tooltip_close {
            get {
                return ResourceManager.GetString("tooltip_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Find next (F3).
        /// </summary>
        public static string tooltip_findNext {
            get {
                return ResourceManager.GetString("tooltip_findNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Find previous (Shift+F3).
        /// </summary>
        public static string tooltip_findPrevious {
            get {
                return ResourceManager.GetString("tooltip_findPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Match case (Alt+C).
        /// </summary>
        public static string tooltip_matchCase {
            get {
                return ResourceManager.GetString("tooltip_matchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Match whole word (Alt+W).
        /// </summary>
        public static string tooltip_matchWholeWord {
            get {
                return ResourceManager.GetString("tooltip_matchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Replace all (Alt+A).
        /// </summary>
        public static string tooltip_replaceAll {
            get {
                return ResourceManager.GetString("tooltip_replaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Replacement term.
        /// </summary>
        public static string tooltip_replacementTerm {
            get {
                return ResourceManager.GetString("tooltip_replacementTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Replace next (Alt+R).
        /// </summary>
        public static string tooltip_replaceNext {
            get {
                return ResourceManager.GetString("tooltip_replaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Search term.
        /// </summary>
        public static string tooltip_searchTerm {
            get {
                return ResourceManager.GetString("tooltip_searchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Toggle to switch between find and replace modes.
        /// </summary>
        public static string tooltip_toggleFindReplaceMode {
            get {
                return ResourceManager.GetString("tooltip_toggleFindReplaceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use Regular Expressions (Alt+E).
        /// </summary>
        public static string tooltip_useRegex {
            get {
                return ResourceManager.GetString("tooltip_useRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The number must be between 1 and {0}.
        /// </summary>
        public static string validation_numberMustBeInRange_format {
            get {
                return ResourceManager.GetString("validation_numberMustBeInRange_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Value must be a number.
        /// </summary>
        public static string validation_valueMustBeNumber {
            get {
                return ResourceManager.GetString("validation_valueMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Replace....
        /// </summary>
        public static string watermark_replacementTerm {
            get {
                return ResourceManager.GetString("watermark_replacementTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Find....
        /// </summary>
        public static string watermark_searchTerm {
            get {
                return ResourceManager.GetString("watermark_searchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Go To Line.
        /// </summary>
        public static string window_title {
            get {
                return ResourceManager.GetString("window_title", resourceCulture);
            }
        }
    }
}
